# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/here/schema/rib/v2/product_compatibility_partition.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'com/here/schema/rib/v2/product_compatibility_partition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import product_compatibility_attributes_pb2 as com_dot_here_dot_schema_dot_rib_dot_v2_dot_product__compatibility__attributes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<com/here/schema/rib/v2/product_compatibility_partition.proto\x12\x16\x63om.here.schema.rib.v2\x1a=com/here/schema/rib/v2/product_compatibility_attributes.proto\"X\n\x11VersionsPartition\x12\x43\n\rcompatibility\x18\x01 \x03(\x0b\x32,.com.here.schema.rib.v2.VersionCompatibilityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.here.schema.rib.v2.product_compatibility_partition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSIONSPARTITION']._serialized_start=151
  _globals['_VERSIONSPARTITION']._serialized_end=239
# @@protoc_insertion_point(module_scope)
